# Generated by Django 3.1.4 on 2020-12-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0002_site'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
    ]
