# Generated by Django 3.1.4 on 2020-12-30 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0003_auto_20201230_1134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
    ]
