# Generated by Django 3.1.4 on 2020-12-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0005_auto_20201230_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='catActief',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='site',
            name='sitActief',
            field=models.BooleanField(default=True),
        ),
    ]
