# Generated by Django 3.1.4 on 2020-12-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0006_auto_20201230_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='catVolgorde',
            field=models.IntegerField(default=0),
        ),
    ]
