# Generated by Django 3.1.4 on 2020-12-31 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0007_categorie_catvolgorde'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['-catActief', 'catVolgorde', 'catOmschrijving']},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['-sitActief', 'categorie', 'sitOmschrijving']},
        ),
        migrations.AlterField(
            model_name='preference',
            name='preStart',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='site',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='launcher.categorie'),
        ),
    ]
