# Generated by Django 3.1.4 on 2020-12-31 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('launcher', '0009_auto_20201231_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='launcher.site'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
